// <auto-generated />
using System;
using CalendarAppointment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarAppointment.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260507112942_UpdateReminderSchema")]
    partial class UpdateReminderSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalendarAppointment.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGroupMeeting")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AppointmentID");

                    b.HasIndex("UserID");

                    b.ToTable("Appointments");

                    b.HasDiscriminator<bool>("IsGroupMeeting").HasValue(false);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CalendarAppointment.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderID"));

                    b.Property<int>("AppointmentID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ReminderID");

                    b.HasIndex("AppointmentID");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("CalendarAppointment.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupMeetingUser", b =>
                {
                    b.Property<int>("GroupMeetingAppointmentID")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantsUserID")
                        .HasColumnType("int");

                    b.HasKey("GroupMeetingAppointmentID", "ParticipantsUserID");

                    b.HasIndex("ParticipantsUserID");

                    b.ToTable("GroupMeeting_Participants", (string)null);
                });

            modelBuilder.Entity("CalendarAppointment.Models.GroupMeeting", b =>
                {
                    b.HasBaseType("CalendarAppointment.Models.Appointment");

                    b.HasDiscriminator().HasValue(true);
                });

            modelBuilder.Entity("CalendarAppointment.Models.Appointment", b =>
                {
                    b.HasOne("CalendarAppointment.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarAppointment.Models.Reminder", b =>
                {
                    b.HasOne("CalendarAppointment.Models.Appointment", "Appointment")
                        .WithMany("Reminders")
                        .HasForeignKey("AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("GroupMeetingUser", b =>
                {
                    b.HasOne("CalendarAppointment.Models.GroupMeeting", null)
                        .WithMany()
                        .HasForeignKey("GroupMeetingAppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarAppointment.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalendarAppointment.Models.Appointment", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("CalendarAppointment.Models.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
